# Site settings
title:          "Luigi Freitas"
callsign:       "PU2SPY"
description:    "Personal Projects Blog"
url:            "https://luigifreitas.me"

# Author
author:
  name:         Luigi Freitas
  url:          https://luigifcruz.me
  email:        luigifcruz@gmail.com

twitter:
  username: luigifcruz
  card: summary

social:
  name: Luigi Cruz
  links:
    - https://twitter.com/luigifcruz
    - https://github.com/luigifcruz
    - https://keybase.io/luigifcruz

# Build settings
markdown:       kramdown

# Katex
katex:
  path_to_js: "./assets/katex.min.js"

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
