baseurl = "https://test.luigi.ltd/"
publishDir = "docs"
languageCode = "en-us"
theme = ["hugo-cloak-email", "terminal"]
paginate = 5
enableRobotsTXT = true

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  favicon = "favicon.ico"
  showLastUpdated = false

[permalinks]
  posts = "/:year-:month-:day/:slug"

[params.twitter]
  creator = "luigifcruz"
  site = "https://twitter.com/luigifcruz"

[imaging]
  resampleFilter = "linear"
  quality = 95
  anchor = "smart"
  bgColor = "#ffffff"

  [imaging.exif]
    disableDate = false
    disableLatLong = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Luigi Cruz - PU2SPY"
    subtitle = "Computer Engineering Student. Radio Amateur (PU2SPY). Interested in Rockets, Satellites and Machine Learning."
    owner = "Luigi Cruz"
    keywords = "Open-Source, Rockets, Satellites, Machine Learning, Raspberry Pi"
    copyright = "© 2020 Luigi F. Cruz"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Luigi Cruz"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "Talks"
        name = "Talks"
        url = "/talks"
      [[languages.en.menu.main]]
        identifier = "Projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "Contact"
        name = "Contact"
        url = "/contact"
