baseurl = "https://luigi.ltd/"
publishDir = "docs"
languageCode = "en-us"
theme = ["hugo-cloak-email", "terminal"]
paginate = 5
enableRobotsTXT = true

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 6
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  favicon = "favicon.ico"
  showLastUpdated = false

[permalinks]
  posts = "/:year-:month-:day/:slug"

[params.twitter]
  creator = "luigifcruz"
  site = "https://twitter.com/luigifcruz"

[imaging]
  resampleFilter = "linear"
  quality = 95
  anchor = "smart"
  bgColor = "#ffffff"

  [imaging.exif]
    disableDate = false
    disableLatLong = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Luigi Cruz - PU2SPY"
    subtitle = "Personal website. Computer Engineering Student. Radio Amateur (PU2SPY). Talking about SDRs, Raspberry Pi, Machine Learning, Parallel Computing, Satellites, Python, C++ and Golang."
    owner = "Luigi Cruz"
    keywords = "SDRs, Raspberry Pi, Machine Learning, Parallel Computing, Satellites, Python, C++, Golang"
    copyright = "© 2020 Luigi Cruz"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Luigi Cruz"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "About"
        name = "About"
        url = "/about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "Projects"
        name = "Projects"
        url = "/projects"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "Contact"
        name = "Contact"
        url = "/contact"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "Donate"
        name = "Donate"
        url = "/donate"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "Twitter"
        name = "Twitter"
        url = "https://twitter.com/luigifcruz"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "Github"
        name = "Github"
        url = "https://github.com/luigifcruz"
        weight = 6
