name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy with Latest Hugo
        uses: victoriadrake/hugo-latest-cd@v1.2
